# Generated by Django 5.0.3 on 2024-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
