# Generated by Django 5.0.3 on 2024-03-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_dish_description_dish_final_price_dish_recipe_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('process_description', models.TextField()),
                ('time', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=25)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='processdescription',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='process_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.process_description'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='ProcessDescription',
        ),
    ]
