# Generated by Django 5.0.3 on 2024-03-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_process_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_description',
            name='stage',
        ),
    ]
