# Generated by Django 5.0.3 on 2024-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_alter_process_description_process_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_description',
            name='dish_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
