# Generated by Django 5.0.3 on 2024-03-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_process_description_dish_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
