# Generated by Django 5.0.3 on 2024-03-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_description',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
        ),
    ]
