# Generated by Django 5.0.3 on 2024-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0014_rename_dish_id_process_description_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='address',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
